name: tvbc_repository
description: A new Flutter package project.
version: 0.0.1
author:
homepage:
publish_to: "none"

environment:
  sdk: '>=2.12.0 <3.0.0'
  




dependencies:    
  dio:    
    git:    
      url: https://github.com/harsimranmaan/dio.git  
      path: dio    
      ref: null-safety 


