name: tvbc_repository
description: A new Flutter package project.
version: 0.0.1
author:
homepage:
publish_to: "none"
 
environment:
  sdk: '>=2.12.0 <3.0.0'
  




dependencies:    
  dio:  ^4.0.6  
    

