name: tvbc_repository
description: A new Flutter package project.
version: 0.0.1
author:
homepage:
publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"
  

dependencies:
  themoviedb_api:
    path: ../themoviedb_api



